apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: hoppscotch
    {{- include "hoppscotch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.frontend }}
  VITE_BASE_URL: {{ .baseUrl | quote }}
  VITE_SHORTCODE_BASE_URL: {{ .shortcodeBaseUrl | quote }}
  VITE_ADMIN_URL: {{ .adminUrl | quote }}
  VITE_BACKEND_GQL_URL: {{ .backendGqlUrl | quote }}
  VITE_BACKEND_WS_URL: {{ .backendWsUrl | quote }}
  VITE_BACKEND_API_URL: {{ .backendApiUrl | quote }}
  VITE_APP_TOS_LINK: {{ .appTosLink | quote }}
  VITE_APP_PRIVACY_POLICY_LINK: {{ .appPrivacyPolicyLink | quote }}
  ENABLE_SUBPATH_BASED_ACCESS: {{ .enableSubpathBasedAccess | quote }}
  {{- end }}{{/* with .Values.frontend */}}
  {{- with .Values.backend }}
  HOPP_AIO_ALTERNATE_PORT: {{ .aioAlternatePort | quote }}
  TOKEN_SALT_COMPLEXITY: {{ .tokenSaltComplexity | quote }}
  MAGIC_LINK_TOKEN_VALIDITY: {{ .magicLinkTokenValidity | quote }}
  REFRESH_TOKEN_VALIDITY: {{ .refreshTokenValidity | quote }}
  ACCESS_TOKEN_VALIDITY: {{ .accessTokenValidity | quote }}
  ALLOW_SECURE_COOKIES: {{ .allowSecureCookies | quote }}
  REDIRECT_URL: {{ .redirectUrl | quote }}
  WHITELISTED_ORIGINS: {{ .whitelistedOrigins | join "," | quote }}
  VITE_ALLOWED_AUTH_PROVIDERS: {{ .allowedAuthProviders | join "," | upper }}
  {{- with .googleAuth }}
  GOOGLE_CALLBACK_URL: {{ .callbackUrl | quote }}
  GOOGLE_SCOPE: {{ .scope | join "," | quote }}
  {{- end }}{{/* with .googleAuth */}}
  {{- with .githubAuth }}
  GITHUB_CALLBACK_URL: {{ .callbackUrl | quote }}
  GITHUB_SCOPE: {{ .scope | join "," | quote }}
  {{- end }}{{/* with .githubAuth */}}
  {{- with .microsoftAuth }}
  MICROSOFT_CALLBACK_URL: {{ .callbackUrl | quote }}
  MICROSOFT_SCOPE: {{ .scope | join "," | quote }}
  MICROSOFT_TENANT: {{ .tenant | quote }}
  {{- end }}{{/* with .microsoftAuth */}}
  {{- with .mailer }}
  MAILER_SMTP_ENABLE: {{ .smtpEnabled | quote }}
  MAILER_USE_CUSTOM_CONFIGS: {{ .useCustomConfigs | quote }}
  MAILER_ADDRESS_FROM: {{ .addressFrom | quote }}
  MAILER_SMTP_HOST: {{ .smtpHost | quote }}
  MAILER_SMTP_PORT: {{ .smtpPort | quote }}
  MAILER_SMTP_SECURE: {{ .smtpSecure | quote }}
  MAILER_TLS_REJECT_UNAUTHORIZED: {{ .tlsRejectUnauthorized | quote }}
  {{- end }}{{/* with .mailer */}}
  {{- with .rateLimit }}
  RATE_LIMIT_TTL: {{ .ttl | quote }}
  RATE_LIMIT_MAX: {{ .max | quote }}
  {{- end }}{{/* with .rateLimit */}}
  {{- end }}{{/* with .Values.backend */}}
  {{- with .Values.enterprise }}
  {{- with .frontend }}
  LOCAL_PROXY_SERVER_ENABLE: {{ .localProxyServerEnabled | quote }}
  PROXY_APP_URL: {{ .proxyAppUrl | quote }}
  {{- end }}{{/* with .frontend */}}
  {{- with .backend }}
  {{- with .githubEnterpriseAuth }}
  IS_GITHUB_ENTERPRISE_ENABLED: {{ .enabled | quote }}
  GITHUB_AUTHORIZATION_URL: {{ .authorizationUrl | quote }}
  GITHUB_TOKEN_URL: {{ .tokenUrl | quote }}
  GITHUB_USER_PROFILE_URL: {{ .userProfileUrl | quote }}
  GITHUB_USER_EMAIL_URL: {{ .userEmailUrl | quote }}
  {{- end }}{{/* with .githubEnterpriseAuth */}}
  {{- with .samlAuth }}
  SAML_ISSUER: {{ .issuer | quote }}
  SAML_AUDIENCE: {{ .audience | quote }}
  SAML_CALLBACK_URL: {{ .callbackUrl | quote }}
  SAML_ENTRY_POINT: {{ .entryPoint | quote }}
  SAML_WANT_ASSERTIONS_SIGNED: {{ .wantAssertionsSigned | quote }}
  SAML_WANT_RESPONSE_SIGNED: {{ .wantResponseSigned | quote }}
  {{- end }}{{/* with .samlAuth */}}
  {{- with .oidcAuth }}
  OIDC_PROVIDER_NAME: {{ .providerName | quote }}
  OIDC_ISSUER: {{ .issuer | quote }}
  OIDC_AUTH_URL: {{ .authorizationUrl | quote }}
  OIDC_TOKEN_URL: {{ .tokenUrl | quote }}
  OIDC_USER_INFO_URL: {{ .userInfoUrl | quote }}
  OIDC_CALLBACK_URL: {{ .callbackUrl | quote }}
  OIDC_SCOPE: {{ .scope | join " " | quote }}
  {{- end }}{{/* with .oidcAuth */}}
  {{- if and .clickhouse .clickhouse.allowAuditLogs }}
  ALLOW_AUDIT_LOGS: {{ .clickhouse.allowAuditLogs | quote }}
  CLICKHOUSE_HOST: {{ .clickhouse.host | quote }}
  {{- end }}{{/* with .clickhouse */}}
  HORIZONTAL_SCALING: {{ .horizontalScalingEnabled | quote }}
  {{- end }}{{/* with .backend */}}
  {{- end }}{{/* with .Values.enterprise */}}
