apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  labels:
    {{- include "hoppscotch.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hoppscotch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "hoppscotch.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hoppscotch.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hoppscotch
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.extraEnvs }}
          env:
            {{- tpl (toYaml .Values.extraEnvs) . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "hoppscotch.fullname" . }}
            - secretRef:
                name: {{ include "hoppscotch.fullname" . }}
      {{- if .Values.waitForDb.enabled }}
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command:
            - 'sh'
            - '-c'
            - |
              end_time=$(($(date +%s) + $0))
              until pg_isready -d $DATABASE_URL; do
                if [ $(date +%s) -ge $end_time ]; then
                  exit 1
                fi
                sleep 2
              done
            - {{ .Values.waitForDb.timeout | default 60 | quote}}
          {{- with .Values.extraEnvs }}
          env:
            {{- tpl (toYaml .Values.extraEnvs) . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "hoppscotch.fullname" . }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
