{{- if .Values.setupDatabaseJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-setup-db" (include "hoppscotch.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: setup-db
    {{- include "hoppscotch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "hoppscotch.labels" . | nindent 8 }}
        app.kubernetes.io/component: setup-db
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
        {{- if .Values.defaultInitContainers.waitForDatabase.enabled }}
        {{- include "hoppscotch.defaultInitContainers.waitForDatabase" . | nindent 8 }}
        {{- end }}
      containers:
        - name: setup-db
          image: {{ include "hoppscotch.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
          args:
            - -c
            - ./node_modules/.bin/prisma migrate deploy
          {{- $extraEnvVars := include "hoppscotch.extraEnvVars" . -}}
          {{- if $extraEnvVars }}
          env:
            {{- $extraEnvVars | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "hoppscotch.fullname" . }}
            {{- include "hoppscotch.extraEnvVarsCM" . | nindent 12 }}
            {{- include "hoppscotch.extraEnvVarsSecret" . | nindent 12 }}
{{- end }}
