{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    {{- include "hoppscotch.labels" . | nindent 4 }}
    app.kubernetes.io/component: hoppscotch
  {{- if .Values.commonAnnotations }}
  annotations:
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ include "hoppscotch.namespace" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hoppscotch.fullname" . }}
{{- end }}
