{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: hoppscotch
    {{- include "hoppscotch.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.backend }}
  {{- if .databaseUrl }}
  DATABASE_URL: {{ .databaseUrl | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ include "hoppscotch.secret.databaseUrl" $ | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ .authToken.jwtSecret | default | b64enc | quote }}
  SESSION_SECRET: {{ .authToken.sessionSecret | b64enc | quote }}
  DATA_ENCRYPTION_KEY: {{ .dataEncryptionKey | b64enc | quote }}
  {{- with .auth.google }}
  GOOGLE_CLIENT_ID: {{ .clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .auth.google */}}
  {{- with .auth.github }}
  GITHUB_CLIENT_ID: {{ .clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .auth.github */}}
  {{- with .auth.microsoft }}
  MICROSOFT_CLIENT_ID: {{ .clientId | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .auth.microsoft */}}
  {{- with .mailer }}
  MAILER_SMTP_URL: {{ .smtpUrl | b64enc | quote }}
  MAILER_SMTP_USER: {{ .smtpUser | b64enc | quote }}
  MAILER_SMTP_PASSWORD: {{ .smtpPassword | b64enc | quote }}
  {{- end }}{{/* with .mailer */}}

  ENTERPRISE_LICENSE_KEY: {{ .enterpriseLicenseKey | b64enc | quote }}

  {{- with .auth.saml }}
  SAML_CERT: {{ .cert | b64enc | quote }}
  {{- end }}{{/* with .auth.saml */}}
  {{- with .auth.oidc }}
  OIDC_CLIENT_ID: {{ .clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .auth.oidc */}}

  {{- if and .clickhouse .clickhouse.allowAuditLogs }}
  CLICKHOUSE_USER: {{ .clickhouse.user | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ .clickhouse.password | b64enc | quote }}
  {{- end }}{{/* with .clickhouse */}}

  {{- if .redisUrl }}
  REDIS_URL: {{ .redisUrl | b64enc | quote }}
  {{- else if or $.Values.redis.enabled $.Values.externalRedis.host }}
  REDIS_URL: {{ include "hoppscotch.secret.redisUrl" $ | b64enc | quote }}
  {{- end }}

  {{- end }}{{/* with .Values.backend */}}
{{- end }}
