apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  labels: {{ include "hoppscotch.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.backend }}
  ################################################################################
  ## Hoppscotch backend parameters
  ################################################################################
  {{- if .databaseUrl }}
  DATABASE_URL: {{ .databaseUrl | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ include "hoppscotch.databaseUrl" $ | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ .jwtSecret | default | b64enc | quote }}
  SESSION_SECRET: {{ .sessionSecret | b64enc | quote }}
  DATA_ENCRYPTION_KEY: {{ .dataEncryptionKey | b64enc | quote }}
  {{- with .googleAuth }}
  GOOGLE_CLIENT_ID: {{ .clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .googleAuth */}}
  {{- with .githubAuth }}
  GITHUB_CLIENT_ID: {{ .clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .githubAuth */}}
  {{- with .microsoftAuth }}
  MICROSOFT_CLIENT_ID: {{ .clientId | b64enc | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .microsoftAuth */}}
  {{- with .mailer }}
  MAILER_SMTP_URL: {{ .smtpUrl | b64enc | quote }}
  MAILER_SMTP_USER: {{ .smtpUser | b64enc | quote }}
  MAILER_SMTP_PASSWORD: {{ .smtpPassword | b64enc | quote }}
  {{- end }}{{/* with .mailer */}}
  {{- end }}{{/* with .Values.backend */}}
  {{- with .Values.enterprise }}
  ################################################################################
  ## Hoppscotch Enterprise parameters
  ################################################################################
  ENTERPRISE_LICENSE_KEY: {{ .licenseKey | b64enc | quote }}
  {{- with .backend }}
  ################################################################################
  ## Hoppscotch Enterprise backend parameters
  ################################################################################
  {{- with .samlAuth }}
  SAML_CERT: {{ .cert | b64enc | quote }}
  {{- end }}{{/* with .samlAuth */}}
  {{- with .oidcAuth }}
  OIDC_CLIENT_ID: {{ .clientId | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .clientSecret | b64enc | quote }}
  {{- end }}{{/* with .oidcAuth */}}
  {{- if and .clickhouse .clickhouse.allowAuditLogs }}
  CLICKHOUSE_USER: {{ .clickhouse.user | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ .clickhouse.password | b64enc | quote }}
  {{- end }}{{/* with .clickhouse */}}
  REDIS_URL: {{ .redisUrl | b64enc | quote }}
  {{- end }}{{/* with .backend */}}
  {{- end }}{{/* with .Values.enterprise */}}
