{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hoppscotch.serviceAccountName" . }}
  namespace: {{ include "hoppscotch.namespace" . | quote }}
  labels:
    {{- include "hoppscotch.labels" . | nindent 4 }}
    app.kubernetes.io/component: hoppscotch
  {{- if or .Values.commonAnnotations .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
