name: CI
on: pull_request
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.x
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Lint charts
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml --lint-conf lintconf.yaml
